### ISSUE TITLE
New Network UI

### ISSUE THREAD

**Issue by dmytrotkk** [skalenetwork/proxy-ui#1]
Migrate to the new version of the Proxy UI - Network UI.

Network UI includes:

- Separate pages for each chain
- Chains metadata, such as logo, color, etc

**Comment by PolinaKiporenko** [comment]
Add the SKALE Chain name hash to boards:

https://mainnet.skalenodes.com/
https://network-demo.skalenodes.com/

For SKALE Chain setup and administration, developers need the SKALE Chain name hash, and very often they create the hash incorrectly. If we have the hash available somewhere either on the board or a list somewhere in github, it would help prevent these mistakes.

Corresponding task - https://github.com/orgs/skalenetwork/projects/6/views/20
